apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api-flask
  namespace: development
  labels:
    app: app-api-flask
    environment: development
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-api-flask
      app.kubernetes.io/name: MyApp
  template:
    metadata:
      labels:
        app: app-api-flask
        app.kubernetes.io/name: MyApp
    spec:
      containers:
      - name: app-api-flask
        image: keilapitangui/app-api-flask:latest
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m"
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
      restartPolicy: Always