apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api-flask-deployment
  labels:
    app: app-api-flask-deployment
    environment: development
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-api-flask
  template:
    metadata:
      labels:
        app: app-api-flask
    spec:
      containers:
      - name: app-api-flask
        image: app-api-flask:latest
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "500m"
        ports:
        - containerPort: 5000