apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-api-flask-hpa
spec:
  scaleTargetRef:
    apiVersion: app/v1
    kind: Deployment
    name: app-api-flask
  minReplicas: 3
  maxReplicas: 6
metrics:
  - type:
    resource:
      name: cpu
    target:
      type: Utilization
      averageUtilization: 50
metrics:
  - type:
    resource:
      name: memory
    target:
      type: Utilization
      averageUtilization: 70